#sftp params mapping with actul prams
sftp:
  param1: userName
  param2: host
  param3: port
  param4: password
#mysql params mapping with actul prams
mysql:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
#clickhouse params mapping with actul prams
clickhouse:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
#mssql params mapping with actul prams
mssql:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
#postgres params mapping with actul prams
postgres:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName